# Generated by Django 3.2.16 on 2022-11-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemFeas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicicleta',
            old_name='imagen',
            new_name='Imagen',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='titulo',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='Descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='Titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
    ]
