# Generated by Django 3.2.16 on 2022-11-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemFeas', '0002_auto_20221103_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicicleta',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='bicicleta',
            old_name='Imagen',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='bicicleta',
            old_name='Titulo',
            new_name='titulo',
        ),
    ]
